Worcester SC Club Championships 25

Session - 1
at
EVENT 401 Female 200m Butterfly              
13 Yrs Age Group - Full Results
Place	Name	AaD	Club		Time			WA Pts	
1.	Thea PICKSTOCK	13	WORM		 3:11.23			244	
14 Yrs Age Group - Full Results
Place	Name	AaD	Club		Time			WA Pts	
1.	Xanthe CARRINGTON-ABRA	14	WORM		 2:58.42			301	
 	Ffion LEA	14	WORM		DNC				
15 Yrs Age Group - Full Results
Place	Name	AaD	Club		Time			WA Pts	
1.	Mia GOOCH	15	WORM		 2:44.31			385	
16 Yrs/Over Age Group - Full Results
Place	Name	AaD	Club		Time			WA Pts	
1.	Asha MAHANTA	17	WORM		 2:27.89			529	
2.	Martha COLVILLE	16	WORM		 2:55.56			316	
3.	Holly SADLER	16	WORM		 3:03.65			276	
